### ISSUE TITLE
The gosec tool found issues in garden-runc-release-1.17.1

### ISSUE THREAD

**Issue by Wayne-H-Ha** [cloudfoundry/garden-runc-release#107]
Comparing with garden-runc-release-1.16.6, the gosec tool is flagging 3 new high severity, medium confidence issues in 1.17.1 with details:
  
Use of weak random number generator (math/rand instead of crypto/rand)

```
{
 "file": "./go/src/garden-runc-release-1.17.1/packages/github.com/containerd/containerd/diff/walking/differ.go",
 "code": "rand.Read(b[:])",
 "line": "179"
},
{
 "file": "./go/src/garden-runc-release-1.17.1/packages/github.com/containerd/containerd/leases/id.go",
 "code": "rand.Read(b[:])",
 "line": "31"
},
{
 "file": "./go/src/garden-runc-release-1.17.1/packages/github.com/containerd/containerd/rootfs/apply.go",
 "code": "rand.Read(b[:])",
 "line": "169"
},
```

Is that OK?

**Comment by BooleanCat** [comment]
Containerd is a dependency we pull in rather than something we own. We are quite quick to update when they ship new versions and are currently using the latest version of their release.

If you'd like someone to look at these items then it would be more appropriate to open an issue on https://github.com/containerd/containerd directly and they may be able to look at these.

On a more meta level - this is the second issue raised as a result of the gosec tool being run over garden - what's the motivation for doing so? If there's some broader obligation to the CF foundation to detect these kinds of things we should have a coonversation about that.

**Comment by Wayne-H-Ha** [comment]
Thanks for the quick response.  We planned to upgrade garden-runc-release from 1.16.6 to 1.17.1.  So we want to check if gosec tool would report any additional issues.  We hope that most of the issues are false alarms.  I will open an issue on containerd to report the above issues.
