### ISSUE TITLE
Container creations block in grootfs create state, leaking grootfs layers locks

### ISSUE THREAD

**Issue by karampok** [cloudfoundry/garden-runc-release#109]
Hi garden team!

## Description

We had an incident in our CF, where cells could not create any more containers and therefore the diego cells became unhealthy (observed  with` cfdot cell-states | grep unexpected` was returning 503). 

In the cells that were in bad state we observed 6 (starting from that number) processes stuck in `grootfs create state`, we could observe for example the following processes
```
root     2612102  3.5  0.0 1227892 18000 ?       S<l  13:39   0:28 /var/vcap/packages/grootfs/bin/grootfs --config /var/vcap/jobs/garden/config/grootfs_config.yml create --disk-limit-size-bytes 2147483648 <removed>
root     2612446  0.0  0.0 890960 11816 ?        S<l  13:39   0:00 /var/vcap/packages/grootfs/bin/grootfs --config /var/vcap/jobs/garden/config/grootfs_config.yml create /var/vcap/packages/cflinuxfs2/rootfs.tar bcb2338e-438e-451a-6dc8-913c-readiness-healthcheck-0
root     2615262  1.3  0.0 1358964 14324 ?       S<l  13:40   0:10 /var/vcap/packages/grootfs/bin/grootfs --config /var/vcap/jobs/garden/config/grootfs_config.yml create --disk-limit-size-bytes 1073741824 <removed> 89c985de-c27f-4a5c-7e9d-814e
root     2615275  0.0  0.0 1045468 11520 ?       S<l  13:40   0:00 /var/vcap/packages/grootfs/bin/grootfs --config /var/vcap/jobs/garden/config/grootfs_config.yml create --disk-limit-size-bytes 1073741824 --exclude-image-from-quota /var/vcap/packages/cflinuxfs2/rootfs.tar edaa101b-b409-4e6b-5408-eac1
root     2615309  0.0  0.0 882764 11820 ?        S<l  13:40   0:00 /var/vcap/packages/grootfs/bin/grootfs --config /var/vcap/jobs/garden/config/grootfs_config.yml create --disk-limit-size-bytes 1073741824 --exclude-image-from-quota /var/vcap/packages/cflinuxfs2/rootfs.tar a5fb495d-af54-45e1-5456-e58b
root     2626787  0.0  0.0 874312 11996 ?        S<l  13:42   0:00 /var/vcap/packages/grootfs/bin/grootfs --config /var/vcap/jobs/garden/config/grootfs_config.yml create /var/vcap/packages/cflinuxfs2/rootfs.tar executor-healthcheck-d1480f80-0db3-4590-795c-c4e95ea93642

```
In the above case, out of the 6 processes, the `strace -p <pid>` gave in 4 of them `futex(ox10d3860 ..`, and in two `flock(6, )` which is the `/vcap/data/grootfs/store/unprivileged/locks/global-lock.lock`. A couple of times, in other unhealthy cells,  we observed that some processes were stuck in a layer lock.

A simple `gaol create -t /path/to/socket -n testme` was also failing because it was never returning.
Doing a `ps -p <>` was giving that 
```
root     2304777  0.0  0.0 497904 13016 ?        S<l  13:37   0:00 /var/vcap/packages/grootfs/bin/grootfs --config /var/vcap/jobs/garden/config/grootfs_config.yml create /var/vcap/packages/busybox/busybox-1.27.2.tar testme
```
The manual gaol creation also failed because it was blocked to global-lock.lock.

Digging more in the `/var/vcap/data/grootfs/store/unprivileged/locks`, we observed a large number of locks also, which are orphaned (`lsof` gives no process has fd to that file), and old.

```
/var/vcap/data/grootfs/store/unprivileged/locks
cell/364710ea-5a12-43be-9635-fea2467a6420:/var/vcap/data/grootfs/store/unprivileged/locks# lsof *
cell/364710ea-5a12-43be-9635-fea2467a6420:/var/vcap/data/grootfs/store/unprivileged/locks# ls -ll |head
total 0
-rw------- 1 root root 0 Nov 29 11:09 001295a51762e4bc679b05f986e7cf81eb789c55fce6e37974b36bdc942bbfe6.lock
-rw------- 1 root root 0 Nov 29 04:12 008fb0d9aa205b1c5cc42d0f42afe87e4c8e9392e48630323110dbd6bfbb1d80.lock
-rw------- 1 root root 0 Nov 11 15:07 009f46a418cb04319a4e94a6efa096aede7276b23aa68e27fdf2c8821e136fb0.lock
-rw------- 1 root root 0 Nov 28 18:46 00d2156518de1da14203b4911d176863d78270e9c16a377b0072bacfb86b3e4f.lock
-rw------- 1 root root 0 Nov 28 20:29 00d8dc496d1ee09368d677d7d6551b65db177326a1f71a68b45e2240571d0f71.lock
-rw------- 1 root root 0 Nov 27 13:45 01ccc5659753f9e3a61a1733e7f0c130e246d5b609acf34a3f428198f37017bb.lock
-rw------- 1 root root 0 Nov 28 17:11 022247641a0c94a9f4d64abac5064983050ecd364ed7cce067ca8972b3e17944.lock
-rw------- 1 root root 0 Nov 29 12:15 023f8df92efed619848e9cd0b6e6d2d7894574eabceae655863c43bbbea6051a.lock
-rw------- 1 root root 0 Nov 28 23:45 02abb94b22ef2fe3dee6a98d9938996af3277fde82ff0a29903b2b9f2a08af8c.lock
cell/364710ea-5a12-43be-9635-fea2467a6420:/var/vcap/data/grootfs/store/unprivileged/locks#ls -ll | wc -1
56
```

Questions: 

1. Do we expect if no container creation is taking place the lock folder to be empty?
2. How many processes can hold the `global-lock.lock` lock?
3. Do you think old locks could have been the root cause?
4. Any idea what else can block grootfs in the create state?

## Environment

* garden-runc-release version:  garden-runc/1.16.7
* IaaS:
* Stemcell version: bosh-vsphere-esxi-ubuntu-trusty-go_agent/3586.52
* Kernel version: 4.4.0-138-generic

## Steps to reproduce
Not really 

## Logs

No errors, latest log entry was `grootfs.create`.
That is a nice script `curl bit.ly/garden-ordnance-survey -sSfL | bash`, I did not know it exists.
Are there any other similar docs/scripts documented somewhere?

## Cause
Not really, we are  investigating that part

## Resolution
Stop the auctioneer, bring all cells back to healthy (because there were no new containers), cleanup locks and mainly scale up the cluster with more cells.

**Comment by yulianedyalkova** [comment]
Hey @karampok, thanks for opening the issue!

### Do we expect if no container creation is taking place the lock folder to be empty?  

Currently it doesn’t look like the lock files get cleaned at any point, so it is normal that you have files in the locks dir. 

### How many processes can hold the global-lock.lock lock? 

There are two operations that use the global lock - create and clean. If you haven’t changed the default behaviour, the create also tries to perform a clean before creating, but only if the threshold is reached. The pure create operation has a shared lock on that file, which means that multiple create operations can run in the same time. So even if there is a blocked create, that shouldn’t affect other creates. The clean operation on the other end has an exclusive lock, so if there is a clean running, nothing else can get the lock in the same time. 

### Do you think old locks could have been the root cause?
I don’t see how that could be a problem - the files themselves should't create any problems if no one is locking on them. 

### Any idea what else can block grootfs in the create state? 
It could be either the create or the clean that blocks the whole flow.

If the clean blocks and never releases the global lock, no create or clean operation can happen in the same time. I quickly went through the code of that command and I didn't find anything obvious that could block forever.

If the create blocks, other creates should be successful unless the threshold is reached. Then every create will block forever on the clean step. The create does a lot of stuff, including using other locks, so it will be shooting in the dark trying to figure out exactly where that could happen.

**Comment by karampok** [comment]
Hi @yulianedyalkova, thx for the reply.

The issue has not been observed again since then, and we have not been able to reproduce it. 
I am closing the issue and re-open if ever appears again.

Thanks again
Konstantinos
