### ISSUE TITLE
Block malicious access to environment variables

### ISSUE THREAD

**Issue by msathe-tech** [cloudfoundry/garden-runc-release#117]
## Description
If a container breakout takes place and what if a malicious code can read /proc/[pid]/environ? In that case attacker can read proc of all containers. This could potentially expose environment variables of other containers. I believe there should be defense in depth provided by Garden apparmor profile by blocking access to /proc/[pid]/environ of other containers.

## Environment

* garden-runc-release version: PAS 2.4 
* IaaS:
* Stemcell version: Ubuntu Xenial 170.14 
* Kernel version: 4.15.0-42-generic 

## Steps to reproduce
This is reg defense in depth for a potential exposure of environment variables of containers on the same host/VM. There is no way to reproduce this as this needs to be a Day 0 vulnerability to demonstrate this leak. 

## Cause

Potential Day 0 vulnerability leading to container breakout of PID and Mount namespace. 

## Resolution

Add defense in depth by adding Deny entry for /proc/[pid]/environ in AppArmor profile for containers created by Garden.

**Comment by BooleanCat** [comment]
Hi Madhav!

Thanks for bringing this up!

When we simply `unshare` into a new user namespace and map to host root, we don't have the capability `CAP_SYS_PTRACE` and so cannot `cat /proc/{pid}/environ` of arbitrary processes.

In order to see environ for a specific process, one of the following must be true:

- The caller and the target process are in the same user namespace, and the caller’s capabilities are a proper superset of the target process’s permitted capabilities.
- The caller has the `CAP_SYS_PTRACE` capability in the target process’ user namespace. (via http://man7.org/linux/man-pages/man2/ptrace.2.html)

Garden containers are always in a user namespace (except privileged containers) and we always drop CAP_SYS_PTRACE.

We did experiment with adding a restriction of /proc/{pid}/environ via apparmor, but we believe this would require more change than is worth it and we'd need to generate a serpate apparmor profile for each container and currently they share a single profile. We looked at similar container managers like docker and we see that they also use a single apparmor profile which doesn't restrict access to other process' environs (via apparmor).
