### ISSUE TITLE
Local file system writing performance degradation after moving from Ubuntu Trusty to Ubuntu Xenial

### ISSUE THREAD

**Issue by giner** [cloudfoundry/garden-runc-release#135]
We have noticed local file system writing performance degradation after moving from Ubuntu Trusty to Ubuntu Xenial based stemcells. We noticed this while pushing a demo for [statping](https://github.com/hunterlong/statping/issues/163) with sqlite as a database driver.

Pusinging:
```
$ cat manifest.yml 
applications:
- name: statping
  docker:
    image: hunterlong/statping:((version))
  timeout: 180
  env: ((env))

$ cf push --var version=v0.80.53 --var env='DB_CONN: sqlite'
```
The result:
```
...
2019-03-29T19:17:15.58+0900 [APP/PROC/WEB/0] OUT INFO: Starting Statping v0.80.53
2019-03-29T19:17:15.63+0900 [APP/PROC/WEB/0] OUT INFO: Statping Database Created
2019-03-29T19:17:16.91+0900 [APP/PROC/WEB/0] OUT INFO: Inserting Sample Data...
2019-03-29T19:17:16.94+0900 [APP/PROC/WEB/0] OUT INFO: Sample data has finished importing
2019-03-29T19:17:16.94+0900 [APP/PROC/WEB/0] OUT INFO: Adding 9900 sample hit records to service Google
2019-03-29T19:19:57.98+0900 [APP/PROC/WEB/0] OUT INFO: Adding 9900 sample hit records to service Statping Github
2019-03-29T19:20:15.75+0900 [HEALTH/0] ERR Failed to make TCP connection to port 8080: connection refused
2019-03-29T19:20:15.75+0900 [CELL/0] ERR Timed out after 3m0s: health check never passed.
...
```

## Environment

* garden-runc-release version: 1.14.0
* IaaS: vSphere
* Stemcell version: 3586.60 (Trusty) -> 170.25 (Xenial)
* Kernel version: 4.4.0-139-generic -> 4.15.0-43-generic

## Steps to reproduce
**ubuntu-trusty**
```
$ cf ssh myapp
vcap@5d3e6c44-4af8-4c12-76a1-7cba:~$ dd if=/dev/zero of=ddtest count=1000 oflag=sync
1000+0 records in
1000+0 records out
512000 bytes (512 kB) copied, 0.0195811 s, 26.1 MB/s
```
**ubuntu-xenial**
```
$ cf ssh myapp
vcap@c085fa91-339f-46f5-4628-8fe5:~$ dd if=/dev/zero of=ddtest count=1000 oflag=sync
1000+0 records in
1000+0 records out
512000 bytes (512 kB, 500 KiB) copied, 5.12301 s, 99.9 kB/s
```

## Cause
The reason for this seems to be the fact that `nobarrier` mount option for xfs is not supported in the recent kernels https://patchwork.kernel.org/patch/9486549.
```
$ sudo dmesg -T | grep nobarrier
[Thu Mar 28 06:07:49 2019] XFS (loop0): nobarrier option is deprecated, ignoring.
[Thu Mar 28 06:07:51 2019] XFS (loop1): nobarrier option is deprecated, ignoring.
```

## Resolution
Assuming we don't care of about consistency of the backing-store file system in the case when VM crashes (this file is recreated on restart as far as I understand) we can disable fsyncs by switching loop block device cache mode to `write through`:
```
echo "write back" > /sys/dev/block/${loopX_device_id}/queue/write_cache
```
This doesn't change the device mode itself however it makes the kernel ignore fsyncs, i.e. it behaves similarly to nobarrier.

Here is how I did it manually (for testing purposes) on Ubuntu Xenial:
```
for mount in /var/vcap/data/grootfs/store/unprivileged /var/vcap/data/grootfs/store/privileged; do
    device_id=$(findmnt -ro MAJ:MIN -nM "$mount")
    sys_path="/sys/dev/block/$device_id"
    write_cache_path="$sys_path/queue/write_cache"
    if [[ $(cat "$write_cache_path") == "write back" ]]; then
        echo "Disabling fsync for $mount"
        echo "write through" | sudo tee "$write_cache_path" > /dev/null && echo OK || echo ERR
    fi
done
```

The result of pusing statping with sqlite after the change:
```
...
2019-03-29T09:52:44.28+0000 [APP/PROC/WEB/0]OUT INFO: Starting Statping v0.80.53
2019-03-29T09:52:44.29+0000 [APP/PROC/WEB/0]OUT INFO: Statping Database Created
2019-03-29T09:52:45.59+0000 [APP/PROC/WEB/0]OUT INFO: Inserting Sample Data...
2019-03-29T09:52:45.59+0000 [APP/PROC/WEB/0]OUT INFO: Sample data has finished importing
2019-03-29T09:52:45.59+0000 [APP/PROC/WEB/0]OUT INFO: Adding 9900 sample hit records to service Google
2019-03-29T09:52:49.71+0000 [APP/PROC/WEB/0]OUT INFO: Adding 9900 sample hit records to service Statping Github
2019-03-29T09:52:53.82+0000 [APP/PROC/WEB/0]OUT INFO: Adding 9900 sample hit records to service JSON Users Test
2019-03-29T09:52:57.92+0000 [APP/PROC/WEB/0]OUT INFO: Adding 9900 sample hit records to service JSON API Tester
2019-03-29T09:53:01.96+0000 [APP/PROC/WEB/0]OUT INFO: Adding 9900 sample hit records to service Google DNS
2019-03-29T09:53:06.10+0000 [APP/PROC/WEB/0]OUT INFO: Migrating Database Tables...
2019-03-29T09:53:06.10+0000 [APP/PROC/WEB/0]OUT INFO: Statping Database Migrated
...
```

## Important note
The issue may not be seen often because normally you don't fsync (see `oflag=sync` in dd command) often to the file system. However making sure that nothing "relies" on the current behavior before upgrading is a bit tricky. The effect of the change is especially visible if max IOPs for a virtual hard drive is limited on the IaaS side (500 IOPs in our case).

**Comment by Callisto13** [comment]
Thanks @giner for opening this issue and highlighting a problem at the XFS level.

As it happens, we [recently investigated](https://www.pivotaltracker.com/story/show/160845774/comments/195629228) changes to OverlayFS between 4.4 and 4.15 after we experienced some performance degradation around our rootfs mount operations. tldr: a commit in 4.10.60 which ensured dirty inodes were correctly synced during syncs or umounts coincided with further (as it turns out faulty) changes to inode writeback threshold behaviour.

While most people are not running `dd`s in their containers, thanks to the change in OverlayFS every time a rootfs is unmounted it does indeed call an `fsync` which may take a while if the amount of dirty data has crossed various thresholds. Our create flow involves unmounting short-lived sidecar containers, and it was the sudden slowness around this which alerted us to performance degradation in Xenial. (This is mitigated somewhat by our new OCI mode feature.)

We have been looking at altering various inode tunables to get around this, but had not considered altering the underlying XFS device; for us the most obvious time sink went into Overlay actions, and I see we only noted the deprecation of `nobarrier` 4 months ago. The combination of no `nobarrier` and the inode stuff has no doubt made this way more fun than any one thing alone :)

A quick test with my script from our slowness investigation shows that setting the `write_cache` to `write through` for the loop device would indeed get around this problem. However, we are hoping to move away from our funky XFS+Loop magic fairly soon, which means that the store will be on EXT4. I _think_ `nobarrier` has also been deprecated there, and I am not sure how keen the other jobs on that same fs will be to disable `fsyncs`. If this is also a problem on EXT4, we may just have to live with it until Canonical fix the dodgy inode writeback threshold behaviour: one problem down.

If we _can_ alter `write_cache` behaviour for the EXT4 device, we will have to review how much we care about consistency of underlying rootfs volumes. All containers are recreated on VM restart (this is configurable but on by default in most customer environments), so we don't care about consistency in Overlay mounts. But we _don't_ recreate the backing store file on restart (any more... not sure what we did way back in 1.14.0), so we may care a little about consistency there... though possibly not much if we were previously using `nobarrier`.
