### ISSUE TITLE
Document our performance tests

### ISSUE THREAD

**Issue by gcapizzi** [cloudfoundry/garden-runc-release#188]

**Comment by georgethebeatle** [comment]
This is one of the low priority stories that we did not pick up, because we felt there is not that much value in it. There is already some info about garden's perf tests [here](https://github.com/cloudfoundry/garden-runc-release/wiki/Testing). They are quite small and there is nothing too special going on there. I am closing this for now. If the new garden team has any trouble with perf tests we might reopen this.
