### ISSUE TITLE
thresholder flakes

### ISSUE THREAD

**Issue by danail-branekov** [cloudfoundry/garden-runc-release#207]
See
https://garden.ci.cf-app.com/teams/main/pipelines/main/jobs/thresholder/builds/403
https://garden.ci.cf-app.com/teams/main/pipelines/main/jobs/thresholder/builds/393

I think those flakes started to appear after introducing the [reserved space for root feature](https://github.com/cloudfoundry/garden-runc-release/issues/202)

**Comment by kieron-dev** [comment]
The tests were changed to use `/` as the example filesystem in https://github.com/cloudfoundry/garden-runc-release/issues/202.

Available space is calculated at the beginning of the suite, and is used in the tests to verify expected values based off it. However, that available space is likely to change due to other containers running on the worker node.

So we create a 20G sparse file, put an ext4 filesystem on it, mount it and use that as the example filesystem in the tests. We can guarantee that it's available space will be stable.

**Comment by kieron-dev** [comment]
I mislabeled the issue on the commit, so here it is: https://github.com/cloudfoundry/garden-runc-release/commit/f5e9feef5003fe7242b33971136682c1147c6d05
