### ISSUE TITLE
OCI hooks

### ISSUE THREAD

**Issue by juaningan** [cloudfoundry/garden-runc-release#55]
Can I use oci hooks with garden?

**Comment by julz** [comment]
Hi @juaningan - no, you can't, garden uses the create/start split rather than OCI hooks. This means you can supply a network-plugin (via the network_plugin bosh property) which will be run to configure the network of the container after it is created but before it is started. We don't support generic plugins or hooks but if you're able to discuss your specific use case for them perhaps we can suggest other ways of achieving the same thing?

**Comment by juaningan** [comment]
Really my usecase is to get kvm acceleration running in runC container in concourse. So I was thinking in OCI hooks to modify the standard config.json that concourse initialize.

**Comment by julz** [comment]
cool! so you have two options there:

1. You can define a [`runtime_plugin`](https://github.com/cloudfoundry/garden-runc-release/blob/develop/jobs/garden/spec#L111) to use a runtime other than `runc`. If you like, this plugin can actually just do stuff to the bundle/config.json and then exec the actual runc binary.
1. You can wait for us to expose `bundle_plugins` which will allow you to define transformations on bundles directly (but that's a little way down our backlog so you may want to go for the first approach!). 

Let us know if you want any help and how you get on: we're always available in #garden channel on slack- good luck!

**Comment by juaningan** [comment]
Ok, perfect thanks a lot. I'll give it a try. Just a question, what is the difference between runtime and image plugin?

**Comment by julz** [comment]
`image_plugin` is responsible for downloading the image (e.g. from docker hub or an OCI registry, using OCI image-spec), `runtime_plugin` is responsible for running it (i.e. it implements OCI runtime-spec, like `runc`).

An example of an image_plugin is [grootfs](http://github.com/cloudfoundry/grootfs). An example of a runtime_plugin is `runc`. 

(Concourse doesn't actually use image plugins, though, since it directly downloads the images with baggage_claim and passes them to us directly).
