### ISSUE TITLE
support user other than vcap

### ISSUE THREAD

**Issue by AmitRoushan** [cloudfoundry/garden-runc-release#58]
Instead of “vcap”, we are maintaining “paas” user for CF module deployment. “paas” user has sudoer permission as well.
Now during “garden” module deployment, “greenskeeper” is expecting “vcap” user and it is hard coded in code.
https://github.com/cloudfoundry/garden-runc-release/blob/master/src/greenskeeper/cmd/greenskeeper/main.go#L20

Is there any plan to make it configurable for other users?

**Comment by julz** [comment]
Hi @AmitRoushan - 

[Garden itself](http://github.com/cloudfoundry/guardian) doesn't hardcode any users, only the bosh release (i.e. this repository) -- which includes `greenskeeper` -- does. It does that because it's a bosh release and bosh is opinionated about users (`vcap`) and directories (`/var/vcap/*`). Greenskeeper is only intended to be used in the bosh release.

If you are setting up garden using something other than bosh you would have to set up directory permissions to fit in with that environment (without using `greenskeeper`), but other than that I would expect things to work. You may also be interested in the standalone no-setup-required `gdn` binary, available on the releases page.

As we're a small team, we unfortunately only have the bandwidth to officially support deployment with bosh, but if you need any help or hit any problems setting things up do feel free to create further issues or stop by the #garden channel in cloud foundry slack and we'll be very happy to help to point you in the right direction.
