### ISSUE TITLE
garden containers resolv.conf

### ISSUE THREAD

**Issue by nsharmacovs** [cloudfoundry/garden-runc-release#59]
i would like to know how does garden container updates its resolv.conf .

i  add "options rotate timeout:1 retries:1" along with NameServer in garden cell /etc/resolv.conf.

Unable to trace the code which modifies the resolv.conf in garden-runc-release (1.4.0)

**Comment by julz** [comment]
Hi @nsharmacovs -

The code for determining the contents of resolv.conf for the container is at [resolv_compiler.go#L12](https://github.com/cloudfoundry/guardian/blob/master/kawasaki/dns/resolv_compiler.go#L12). 

The tl;dr is we copy all the lines from the host resolv.conf that aren't `nameserver 127.*` (because those lines never make sense in a container) in to the container (on creation, the resolv.conf is never updated in a running container). 

Note that this only happens if (a) you don't specify any `dns_servers` in garden's properties -- if you do then we ignore the host resolv.conf, (b) you aren't using a `network_plugin` (in the latest `cf-deployment` the container-networking network plugin is used) -- if you do then it's up to that plugin what resolv.conf we create.
