### ISSUE TITLE
garden health check failing

### ISSUE THREAD

**Issue by AmitRoushan** [cloudfoundry/garden-runc-release#61]
I am working on CF V287 deployment. I am facing a strange error in garden health check.
Following are the system/issue info:
  OS: 14.04, Trusty Tahr
  Kernel version:  4.4.0-105-generic
  diego-release version 2.0.0
  garden-runc-release version 1.11.1

Issue log:
```
{"timestamp":"1521155111.438632011","source":"guardian","message":"guardian.run.exec.execrunner.runc","log_level":0,"data":{"handle":"executor-healthcheck-a51bbaf6-b013-4d85-438b-3f6a1cde4b7d","id":"executor-healthcheck-a51bbaf6-b013-4d85-438b-3f6a1cde4b7d","message":"exec_ failed: container_linux.go:348: starting container process caused \"chdir to cwd (\\\"/home/vcap\\\") set in config.json failed: permission denied\"\n","path":"/bin/sh","session":"9.2.1"}}

Please help on this issue? 
Thanks in Advance. +1

Best Regards
Amit

**Comment by teddyking** [comment]
Hi @aminjam, are you using cf-release to deploy this? And is there a particular reason you're using diego-release 2.0.0?

The release notes for cf-release v287 specify diego-release v1.34.0 and garden-runc-release v1.11.1. It looks like you might just be using incompatible versions of components.

**Comment by AmitRoushan** [comment]
@teddyking , That mistake from my side. I am using CF-Deployment(v1.19.0).

**Comment by julz** [comment]
Hi @AmitRoushan  - this seems like it would have to be an issue higher up than garden: it's complaining that `/home/vcap` is inaccessible, which would presumably only happen if the rootfs had incorrect permissions. What stemcell version are you using? Does the error still occur after a `bosh recreate`?

**Comment by AmitRoushan** [comment]
@julz , We majorly use saltstack for our deployment. So we have ported bosh script to salt script. Also we are maintaining 'paas' user in deployment VM for deployment instead 'vcap' user. But we still maintain 'vcap' user inside container. Following are permission for different directory in rootfs:
```
drwxr-x--- 21 root root 4096 Mar 15 06:53 ./
drwxr-x---  3 root root 4096 Mar 12 17:24 ../
lrwxrwxrwx  1 root root   14 Feb 21 20:43 app -> /home/vcap/app
drwxr-xr-x  2 root root 4096 Feb 21 20:38 bin/
drwxr-xr-x  2 root root 4096 Apr 11  2014 boot/
drwxr-xr-x  4 root root 4096 Feb 21 20:43 dev/
-rwxr-xr-x  1 root root    0 Feb 21 20:43 .dockerenv*
drwxr-xr-x 81 root root 4096 Feb 21 20:43 etc/
drwxr-xr-x  3 root root 4096 Feb 21 20:43 home/
drwxr-xr-x 13 root root 4096 Feb 21 20:38 lib/
drwxr-xr-x  2 root root 4096 Jan 24 01:02 lib64/
drwxr-xr-x  2 root root 4096 Jan 24 01:00 media/
drwxr-xr-x  2 root root 4096 Apr 11  2014 mnt/
drwxr-xr-x  2 root root 4096 Jan 24 01:00 opt/
drwxr-xr-x  2 root root 4096 Apr 11  2014 proc/
drwx------  3 root root 4096 Feb 21 20:43 root/
drwxr-xr-x  8 root root 4096 Jan 26 02:22 run/
drwxr-xr-x  2 root root 4096 Feb 21 20:38 sbin/
drwxr-xr-x  2 root root 4096 Jan 24 01:00 srv/
drwxr-xr-x  2 root root 4096 Mar 13  2014 sys/
drwxrwxrwx  2 root root 4096 Mar 15 06:53 tmp/
drwxr-xr-x 10 root root 4096 Jan 24 01:00 usr/
drwxr-xr-x 12 root root 4096 Feb 21 20:43 var/

Thank you!!!

**Comment by julz** [comment]
Hi @AmitRoushan -

 I'm afraid it's quite difficult for us to support non-bosh deployments. In this case I suspect what's happened is in recent versions of garden we expect the rootfs to be provided as a tar file rather than a directory. 

You can see the changes that were made in `cf-deployment` for that change [here](https://github.com/cloudfoundry/cf-deployment/commit/461e822d0a04653daf55b48e6b46370700d7f6f0#diff-f39617caec1965e56248ce1bf556db4dR1090) -- in particular see that the `preloaded_rootfses` property in Diego changed from `cflinuxfs2:/var/vcap/packages/cflinuxfs2/rootfs` to `cflinuxfs2:/var/vcap/packages/cflinuxfs2/rootfs.tar`. A [similar change was made](https://github.com/cloudfoundry/diego-release/commit/f5dd071ee1b2d1cdf948ea1933807cc19303fd77) in the `diego-release` manifest generation scripts, although those are now deprecated in favour of cf-deployment.

You will need to modify your salt stack scripts along similar lines to the cf-deployment manifest changes above to use recent versions of garden.

Thanks!
