### ISSUE TITLE
QUESTION: Can the CRIU library be packaged along with the garden-runc release?

### ISSUE THREAD

**Issue by abh1kg** [cloudfoundry/garden-runc-release#72]
Hi there! Thanks for taking time to open an Issue.
Please fill out as much of the following information as you can.

# Description
Since `runc` depends on a CRIU installation to perform checkpoint and restore of running containers, can the `criu` distribution be packaged along with the release? 

# Environment
Cloud Foundry
* garden-runc-release version: Any
* IaaS: Any
* Stemcell version: Any
* Kernel version: (`uname -r` prints this information)

**Comment by teddyking** [comment]
Hey @abh1kg, garden doesn't currently support checkpoint and restore for containers right now, so there's no need for us to package up `criu` with the release. We do occasionally get asked about this though. Out of interest what are you looking to with checkpoint/restore?

**Comment by abh1kg** [comment]
@teddyking One of the reasons I wanted to use `criu` was to be able to migrate in-flight TCP connections to another up-and-coming Garden container as part of a blue-green deployment workflow. Such TCP connections include stuff like SSH connections/Websocket connections etc.
Out of curiosity, why doesn't Garden support checkpoint and restore though? Since it is `runc`-compliant and `runc` supports `criu` operations out of the box, I was assuming it to be also available for Garden containers. I can understand the entire workflow and support not being there directly from Cloud Foundry but wouldn't one be able to log on to a diego cell and run the checkpoint operations manually?

**Comment by julz** [comment]
Hi @abh1kg, there's no reason you couldn't manually run `criu` (as you say it's all just runc under the covers!), but it's not something we support or that Diego/cloud foundry exposes to users. The reason for that is the CF model is to have stateless apps so we can automatically patch and manage the cluster easily. You can do a blue/green deployment by deploying the new version of your application in CC and then swapping the route over using `cf map-route` without needing checkpoint/restore. Also, when hosts are upgraded, Diego first ensures there's enough new instances of your apps on other cells before shutting down a cell to upgrade. Since all the instances should be equivalent and stateless there's generally no need in CF to worry about a serialising the memory of one particular container of an app, and it introduces a lot of complexity to the scheduling and container lifecycle if we have to deal with rescheduling running containers instead of treating them as immutable, stateless and replaceable.

Having said that if you want to experiment with criu on a garden cell there's no obvious reason it won't work (you'll have to install the binary yourself, perhaps in your own bosh release), and feel free to drop by the #garden channel on cf slack if we can help!
