### ISSUE TITLE
Garden crashed during pea cleanup

### ISSUE THREAD

**Issue by gcapizzi** [cloudfoundry/garden-runc-release#96]
# Description

An upgrade of `cf-deployment` is failing because of Garden becoming unavailable after redeploying a `diego-cell`. In particular, Garden seems to be stuck while trying to kill an Envoy sidecar, which won't die as it is in permanent D-state.

# Environment

These are the versions after the upgrade:

* garden-runc-release version: `1.16.4`
* IaaS:
* Stemcell version:
* Kernel version: `Linux da5c5f18-2b63-40a2-adf7-05a29e978c6a 4.15.0-33-generic #36~16.04.1-Ubuntu SMP Wed Aug 15 17:21:05 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux`

This cell is using Garden with containerd.

# Steps to reproduce

This occurred while upgrading `cf-deployment`.

# Logs

The output of ordnance survey can be downloaded [here](https://drive.google.com/file/d/1V3A7dznMvUX0BtmimhBFTo0xEJoAZkIK).

# Cause

The cause is still unknown.
Garden is trying to clean up containers on start, but one of the containers, which is a pea running Envoy, can't be killed as the Envoy process is in D-state. The forest shows a `runc kill` process that has been running for hours.

We didn't perform the reproduction steps specified in the [D-state document](https://docs.google.com/document/d/1Ph7j__TJco1ZO592re3fJyCCP-kgyfd2YRxLRD_IzFU/edit#) this time, we should do it the next time this happens.

**Comment by sunjayBhatia** [comment]
This issue tends to present itself in cloudfoundry as a problem with the cell `rep` which is a bit of a red herring:

- the `rep` does not serve requests until it can communicate with `garden`
- `garden` does not bind to a socket/port until its startup deletion of remaining containers completes
- the `rep` process has a `post-start` check that hits the `ping` endpoint on the `rep` that fails when `garden` gets in the state this issue is concerned with

Can we change around `garden`'s startup/monit behavior to make it more obvious to operators that `garden` is failing?

**Comment by BooleanCat** [comment]
@sunjayBhatia 

We're looking at how monit reports on garden when the gdn process is alive but monit is unable to makea connection to the garden port (or socket). Currently our monit file looks like this:

```
...
  if failed unixsocket /var/vcap/data/garden/garden.sock
    with timeout 5 seconds for 12 cycles
    then restart
...
```

When we deliberately change this port to be wrong, we observe that monit reports garden as either `not monitored` or `connection failed` on a loop with the status changing roughly every 10 seconds.

From an operator point of view - this would be a pretty clear indication that garden is having a bad time. Is there some other situation we're missing here whereby garden was reported as being healthy by monit yet unable to create containers?

**Comment by sunjayBhatia** [comment]
@BooleanCat 

> garden does not bind to a socket/port until its startup deletion of remaining containers completes

When deletion of orphaned container takes a long time on start up (or never completes), we see that BOSH reports the `rep` as being unhealthy (b/c the `rep` cannot talk to garden so it fails) when in reality `garden` was never available. I would have to reproduce it again but I believe `monit` reports `garden` as healthy until (every minute) it restarts the job (and the job gets stuck deleting containers again).

**Comment by sunjayBhatia** [comment]
The Diego team knows where to look to diagnose this problem when the `rep` is reported as unhealthy, but it would be nice if operators could see where the actual issue is.

Is it a common practice in BOSH releases for the `monit` script itself to restart the job? Could you remove that line and let the BOSH agent decide when to do that? It may be able to detect the failing job that way?

**Comment by BooleanCat** [comment]
> I would have to reproduce it again but I believe monit reports garden as healthy until (every minute) it restarts the job

What we observed when forcing that monit check to fail was that monit reported the state as "not monited" or "connection failure". We think that forcing a connection failure in the unixsocket check should look similar (to monit) as garden being up but not responding. Maybe there was more to the original issue if you were seeing something different?

> Is it a common practice in BOSH releases for the monit script itself to restart the job?

This I don't know and could buy that maybe we should just let it fail and not restart.

The commit that added the `then restart` line looks like the init commit for the repo, the commit message just says "it's a bosh release!" lol.

@julz Maybe we shouldn't have garden's monit script restart the garden monit job if we consistently fail to talk to garden on its socket/port? Seems like a persistent failure like that should involve operator intervention?

**Comment by sunjayBhatia** [comment]
I added an hour long sleep here: https://github.com/cloudfoundry/guardian/blob/0f7e75fe67bc7213e281c968caa2b64bbf1f079c/gardener/gardener.go#L483 to simulate deleting existing containers on start up taking a long time and that reproduces the issue in CF.

I think the key here is that `garden` is considered by `monit` and BOSH to already be running b/c it has a pidfile that gets written [here](https://github.com/cloudfoundry/garden-runc-release/blob/142918c6d8adf3b24e2c8ec993f7071ab3c2ad12/jobs/garden/templates/bin/garden_start.erb#L74) even though it isn't actually operational. As a result, BOSH moves on to running the `post-start` for the `rep` which fails. If we could short circuit this and not allow BOSH to move on to running `post-start` scripts until `garden` is in fact working properly that would solve the problem. We could also instead of using `monit` use a `post-start` script in `garden` and `garden-windows` similar to the `rep`'s to fail the job if the server does not come up in some configured time.

**Comment by julian-hj** [comment]
Today we are seeing something very similar in the persi ci pipeline.  Garden doesn't crash in pea cleanup, but seems to linger in container cleanup until monit grows impatient and sends a SIGQUIT.

This seems to belong to a class of issues stemming from containerd being too polite to terminate stuck containers.  I think #108 is perhaps a different manifestation of the same issue.

Anyway, here's the ordnance survey:
[os-report.tar.gz](https://github.com/cloudfoundry/garden-runc-release/files/2634709/os-report.tar.gz)

**Comment by julian-hj** [comment]
...and just like with #108 running `monit stop containerd` followed by `pkill --signal 9 containerd` appears to mop up all the sleeping containers, after which everything can be started up again nicely.

it doesn't appear that any of the stuck containers was in d state, but `pkill containerd` didn't do anything, so it doesn't seem like they are responding to SIGTERM but SIGKILL works.

**Comment by Callisto13** [comment]
The symptoms here point to this being the same as https://github.com/cloudfoundry/garden-runc-release/issues/121
